[flavor]
dark = "flexoki-dark"

[icon]
prepend_dirs = [
  {name = "Applications", text = "", fg = "#CECDC3"},
  {name = "Cursor",       text = "C", fg = "#CECDC3"},
  {name = "ZoteroApp",    text = "Z", fg = "#CECDC3"},
  {name = "Scripts",      text = "", fg = "#CECDC3"},
  {name = "Servers",      text = "", fg = "#CECDC3"},
]
