hl.on("hyprland.start", function()
	hl.exec_cmd("waybar & hyprpaper")
	hl.exec_cmd("kanshi")
	hl.exec_cmd("calcurse --daemon")
	hl.exec_cmd("wl-clipboard-history -theme")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("rm '~/.cache/cliphist/db'")
	hl.exec_cmd("cliphist wipe")
	hl.exec_cmd("hyprctl setcursor Banana 24")
	hl.exec_cmd("gsettings set org.gnone.desktop.interface color-scheme 'prefer-dark'")
	hl.exec_cmd("gsettings set org.gnone.desktop.interface gtk-theme  'prefer'")
	hl.exec_cmd("playerctl daemon")
	hl.exec_cmd("eww daemon")
	hl.exec_cmd("fcitx5 -d")
	hl.exec_cmd("fcitx5-remote -r")
end)
